[package]
name = "t-machine"
version = "0.1.0"
authors = ["3to5thpower <nisi3genki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
